### ISSUE TITLE
БЭМ, компонентность

### ISSUE THREAD

**Issue by Sergio-Ka** [EvgeniyChuprov/CV#2]
1. Все блоки по БЭМ реализовать в виде миксинов. Каждый блок поместить в отдельную папку со всеми его реализациями (в смысле разметка, стили, картинки если есть, js код и тд) В этой кстати связи нужно понять что иконки каждого блока это часть реализации блока header, а значит должны находится в его папке в подпапке images, например. Лучше для блоков создать подпапку blocks и уже в нее ложить все блоки (которые по БЭМ и миксинами реализованы). Структура должна быть древовидная - основной блок подключает блоки помельче, те в свою очередь другие блоки и так далее. Параметры передаются сверху от корня в виде объектов (такой подход даст нам возможность и назначить дефолтные значения, и передавать не все параметры, и проверять значения на валидность без лишних движений при деструктуризации в самих блоках). Короче, тут должен быть реализован компонентный подход подобный подходу, применяемому в реакте, но на миксинах. Сейчас дробление слишком мелкое. Например взять блок образование:
```
      .education-block
        +practice({title:'master degree', data:'// Feb 2011 - Jun 2014', name:'university name', text: text})
        +practice({title:'master degree', data:'// Feb 2011 - Jun 2014', name:'university name', text: text})
        +practice({title:'master degree', data:'// Feb 2011 - Jun 2014', name:'university name', text: text})
        +practice({title:'master degree', data:'// Feb 2011 - Jun 2014', name:'university name', text: text})
```
Ужасно. А если будет 100 образований, каждый раз будем сто вызовов миксина писать, каждый со своими параметрами или лучше на вход более крупного блока подадим объект (читай прилетевший с сервера json) и он нам сам там внутри проитерируется по пунктам?
2. Блоки инклюдить непосредственно в каждом блоке который их использует, в начале файла. ТАк же потом будет происходить подключение модулей в реакте. Это принятый стиль, кроме того удобен для восприятия. Всякие extends убрать. Это используется при разработке многостраничных сайтов, а здесь одна страница, каждый инструмент хорош к месту. Содержимое файла template.pug переместить в index.pug, а в нем вызывать миксин обертки .content, а уже в нем вызывать миксины блоков.
3. Папку reset убрать вместе с содержимым. Она нам дает не очевидное поведение, тем более что не понятно на каком месте эти свойства воткнутся, ведь как известно для двух одинаковых свойств, срабатывает свойство написанное последним. Если нужно обнулить отступы - это можно делать либо непосредственно в блоках, которых нужно либо в файле style.css через универсальный селектор, который имеет самый маленький вес.
4. Разные свойства одного и того же компонента навешиваются через модификаторы БЭМ. Использовать инлайновые стили для кода который не генерируется в js - дурной тон, а если точнее не очевидное поведение. Кроме того БЭМ не зря используется тут. Поэтому вот такое не пойдет:
```
mixin skills (parametr)
  .skills 
    h3.skills__name= parametr.name
    ul.skills__line
      - for (var i=0; i<parametr.maxValue; i++) 
        if i < parametr.value
          li
          div(class="ring" style={background: '#3d6cb0'})  
        else
          li
          div(class="ring" style={background: '#e6e6e6'})
```
Тут кстати глянуть не только для этого блока, но и в остальном проекте. В случае с software можно оставить, так как там по другому будет сложно реализовать.

**Comment by Frolikow** [comment]
Дополню.
Подобное именование не допустимо  в рамках БЭМа:
![image](https://user-images.githubusercontent.com/25764783/59322519-a9374980-8d00-11e9-9c96-dab810939370.png)
Если не до конца понимаешь как правильно именовать, лучше разобраться в этом на начальном этапе, чтоб не переписывать много раз одни и те же вещи.

**Comment by Sergio-Ka** [comment]
В принципе сделано не плохо, но все еще есть ряд замечаний:
1. 
```
.content
    .content__left
```
.content__left тут явно не элемент, а элемент с модификатором, называть элемент словом left не очень хорошая практика в именовании. Тут должно быть что-то вроде:
```
.content
    .content__column.content__column_position_left
    .content__column.content__column_position_right
```
При этом content__column будет содержать общие стили, если нужны, а модификаторы только те, которые нужны непосредственно для позиционирования.
2. Едва ли это можно считать хорошей практикой БЭМ:
```
  .skills
    each item in skills
      .skills__block
        h3.skills__name= item.name
        ul.skills__line
          - for(let i = 0; i < item.maxValue; i += 1) {
            -if(i < item.value){
              li.ring
            -}else{
              li.ring.ring-gray
            -};
          -};
```
Тут ring явно элемент блока skills, и если он даже блок отдельный по БЭМ (в чем я очень сильно сомневаюсь), то его надо в отдельную папку выносить со всеми его реализациями. Кроме того такое по БЭМ не допустимо li.ring.ring-gray. Не понятно даже что это, если модификатор то надо так li.ring.ring_color_gray., если микс то их нельзя в БЭМ использовать.
То же самое кстати и в блоке software для color:
```
.software
    each item in software
      .software__block
        h3.software__title= item.name
        .software__points
          .color(style={width:""+item.percent})
```
3. В блок logo параметры по прежнему передаются не в виде объекта, декомпозиция не делается:
```
mixin logo(name, surname, job)
  .logo
    .logo__ring
    .logo__name= name
    .logo__surname= surname
    .logo__job= job
```
4. 
```
.color(style={width:""+item.percent})
```
Тут и вообще в подобных случаях использовать темплейт строки вместо конкатенации, то есть типа:
```
.color(style=`width: ${item.percent};`)
```
5. Тут тег strong не слишком подходит, лучше span:
```
p.profile__text= text
      strong.profile__text-strong= strongText
```
