### ISSUE TITLE
Именование подключаемых файлов

### ISSUE THREAD

**Issue by Sergio-Ka** [EvgeniyChuprov/CV#3]
Посмотреть в стандартах, как именуются подключаемые файлы, если нет каких-то особых договоренностей в проекте (а их в данном случае нет) и переименовать файлы шрифтов в соответствии с этим.

**Comment by Sergio-Ka** [comment]
Вынести папку fonts в src из blocks, так как по смыслу тут шрифты явно не блок БЭМ и вообще не блок. После вынесения issue можно закрыть.

**Comment by EvgeniyChuprov** [comment]
Перенес папку fonts в src из blocks.
