### ISSUE TITLE
Стиль кода

### ISSUE THREAD

**Issue by Sergio-Ka** [EvgeniyChuprov/CV#4]
1. Обычно использование ключевого слова var плохо, так как оно загрязняет глобальную область видимости. И даже если переменная должна быть в этой области видимости, то к ней обращаются как к свойствам глобального объекта window. Короче использовать let или const в данных случаях. При этом const всегда лучше, так как не позволяет переназначать значение переменной, как следствие код становится более устойчивым к ошибкам, понятно, что если это переменная по сути то нормально использовать и let. 
2. Нужно посмотреть, где то используются двойные кавычки для текстовых . значений " а где-то одинарные '. Для js нужно использовать одинарные, для например атрибутов тегов двойные.
3. В Pug то, что экранируется знаком - это js код по факту. А там принято в конце строки ставить точку с запятой. Лучше сразу приучать себя писать красиво и в одном стиле.
4. i++ в таком случае принято писать i+=1.
Это все есть в стандартах (ссылка на стайлгайд от AirBnB).

**Comment by Frolikow** [comment]
В начале рефакторинга добавлю по код-стайлу : 
Когда пишешь стили, не стесняйся каждый блок правил отделять пустой строкой) 
В pug'e это правило касается блоков, которые можно выделить по смыслу 
И на будущее - в js тоже нужно разделять, между всеми функциями отступ добавлять,  и внутри функций тоже добавлять, например между объявлением переменных, действием и `return`ом

Это все значительно повысит читаемость кода

**Comment by Sergio-Ka** [comment]
1. @media должны быть отделены пустой строкой, правила начинающиеся с амперсанда тоже:
```
    .ring{
      background:$blue-color;
      border-radius: 50%;
      width: 1.7rem;
      height: 1.7rem;
      position: relative;
      &-gray{
        background:#e6e6e6;
      }
    }
```
2. else, if, for отделяются пробелами:
```
  .skills
    each item in skills
      .skills__block
        h3.skills__name= item.name
        ul.skills__line
          - for(let i = 0; i < item.maxValue; i += 1) {
            -if(i < item.value){
              li.ring
            -}else{
              li.ring.ring-gray
            -};
          -};
```
3. при коммитах в гите нужно указывать в теле коммита "#номер_issue", тогда коммит будет отображаться в том issue, номер которого указан. А то не понятно, делалось что-то по issue или нет.
