### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by Frolikow** [EvgeniyChuprov/CV#6]
Все, прилетающие в миксин, данные, нужно деструктурировать.
Что тебе это даст:
1) Сразу, в начале файла, будет видно что за переменные лежат в прилетевшем объекте
2) Исчезнет дублирование, как например здесь:
![image](https://user-images.githubusercontent.com/25764783/59322732-cd475a80-8d01-11e9-955d-6958ea25f3f1.png)
в каждой строке упоминаешь про `parametr`(и я не уверен что такое слово существует)

**Comment by Sergio-Ka** [comment]
Тут надо покрасивше сделать, чем уже сделано. Деструктуризация прям в параметрах хорошо (как в блоке контактов, например), но тут где-то сделано так, где-то  как в блоке header вообще не объект даже передается. Надо привести все блоки к одному стилю кода. Тут еще бы не дурно сделать вообще валидацию на передаваемое значение, и назначать параметрам значения по умолчанию. А то где-то сделано значения по умолчанию, где-то нет. Тут единственное можно исключить блоки, которые просто обертки и параметры внутрь передают, типа education/experience.

**Comment by Sergio-Ka** [comment]
Думаю можно закрыть этот issue
